// <auto-generated />
using ECommerce.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.DataAccess.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260801160559_AddProductImages")]
    partial class AddProductImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "帳篷與天幕"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "睡眠裝備"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "露營家具"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "炊具與餐具"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "照明與電源"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "戶外服飾"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "戶外配件"
                        });
                });

            modelBuilder.Entity("ECommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "適合三至四人使用的雙層家庭帳篷，具備防潑水外帳與通風紗網。",
                            IsActive = true,
                            ListPrice = 12800m,
                            Price = 10800m,
                            Price10 = 9500m,
                            Price5 = 10200m,
                            SKU = "TENT-001",
                            StockQuantity = 20,
                            Title = "星野四人家庭帳篷"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "厚度 8 公分的自動充氣睡墊，適合露營與車宿使用。",
                            IsActive = true,
                            ListPrice = 3200m,
                            Price = 2680m,
                            Price10 = 2300m,
                            Price5 = 2500m,
                            SKU = "SLEEP-001",
                            StockQuantity = 40,
                            Title = "自動充氣露營睡墊"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "輕量鋁合金桌板，可快速折疊收納，適合二至四人使用。",
                            IsActive = true,
                            ListPrice = 2800m,
                            Price = 2380m,
                            Price10 = 2050m,
                            Price5 = 2200m,
                            SKU = "FURN-001",
                            StockQuantity = 30,
                            Title = "鋁合金折疊露營桌"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "包含湯鍋、平底鍋、杯具與收納袋，適合兩至三人露營使用。",
                            IsActive = true,
                            ListPrice = 1800m,
                            Price = 1480m,
                            Price10 = 1280m,
                            Price5 = 1380m,
                            SKU = "COOK-001",
                            StockQuantity = 50,
                            Title = "戶外不鏽鋼炊具組"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            Description = "適合春秋露營穿著的輕量外套，具備防風與基本防潑水功能。",
                            IsActive = true,
                            ListPrice = 2600m,
                            Price = 2180m,
                            Price10 = 1850m,
                            Price5 = 1980m,
                            SKU = "WEAR-001",
                            StockQuantity = 60,
                            Title = "輕量防風防潑水外套"
                        });
                });

            modelBuilder.Entity("ECommerce.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ECommerce.Models.Product", b =>
                {
                    b.HasOne("ECommerce.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Models.ProductImage", b =>
                {
                    b.HasOne("ECommerce.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
