// <auto-generated />
using System;
using ECommerce.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.DataAccess.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815060336_AddPaymentTransaction")]
    partial class AddPaymentTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ECommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "帳篷與天幕"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "睡眠裝備"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "露營家具"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "炊具與餐具"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "照明與電源"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "戶外服飾"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "戶外配件"
                        });
                });

            modelBuilder.Entity("ECommerce.Models.HeroBanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("MobileImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("HeroBanners");
                });

            modelBuilder.Entity("ECommerce.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ECommerce.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewebPayTradeNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("ECommerce.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MerchantOrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NewebPayTradeNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantOrderNo")
                        .IsUnique();

                    b.HasIndex("OrderHeaderId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("ECommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "適合三至四人使用的雙層家庭帳篷，具備防潑水外帳與通風紗網。",
                            IsActive = true,
                            ListPrice = 12800m,
                            Price = 10800m,
                            Price10 = 9500m,
                            Price5 = 10200m,
                            SKU = "TENT-001",
                            StockQuantity = 20,
                            Title = "星野四人家庭帳篷"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "厚度 8 公分的自動充氣睡墊，適合露營與車宿使用。",
                            IsActive = true,
                            ListPrice = 3200m,
                            Price = 2680m,
                            Price10 = 2300m,
                            Price5 = 2500m,
                            SKU = "SLEEP-001",
                            StockQuantity = 20,
                            Title = "自動充氣露營睡墊"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "輕量鋁合金桌板，可快速折疊收納，適合二至四人使用。",
                            IsActive = true,
                            ListPrice = 2800m,
                            Price = 2380m,
                            Price10 = 2050m,
                            Price5 = 2200m,
                            SKU = "FURN-001",
                            StockQuantity = 10,
                            Title = "鋁合金折疊露營桌"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "包含湯鍋、平底鍋、杯具與收納袋，適合兩至三人露營使用。",
                            IsActive = true,
                            ListPrice = 1800m,
                            Price = 1480m,
                            Price10 = 1280m,
                            Price5 = 1380m,
                            SKU = "COOK-001",
                            StockQuantity = 20,
                            Title = "戶外不鏽鋼炊具組"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            Description = "適合春秋露營穿著的輕量外套，具備防風與基本防潑水功能。",
                            IsActive = true,
                            ListPrice = 2600m,
                            Price = 2180m,
                            Price10 = 1850m,
                            Price5 = 1980m,
                            SKU = "WEAR-001",
                            StockQuantity = 60,
                            Title = "輕量防風防潑水外套"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "適合雙人露營與登山使用的輕量雙層帳篷，具備良好通風與防潑水能力。",
                            IsActive = true,
                            ListPrice = 6800m,
                            Price = 5680m,
                            Price10 = 4980m,
                            Price5 = 5350m,
                            SKU = "TENT-002",
                            StockQuantity = 25,
                            Title = "森境雙人輕量帳篷"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "大型六角天幕提供寬廣遮蔽空間，適合家庭露營與多人活動使用。",
                            IsActive = true,
                            ListPrice = 5200m,
                            Price = 4380m,
                            Price10 = 3850m,
                            Price5 = 4100m,
                            SKU = "TENT-003",
                            StockQuantity = 15,
                            Title = "黑岩戶外六角天幕"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "適合春秋與低溫露營使用的羽絨睡袋，輕量且方便壓縮收納。",
                            IsActive = true,
                            ListPrice = 4600m,
                            Price = 3980m,
                            Price10 = 3500m,
                            Price5 = 3750m,
                            SKU = "SLEEP-002",
                            StockQuantity = 35,
                            Title = "四季保暖羽絨睡袋"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "人體工學弧形充氣枕，可快速充放氣，收納後體積小巧。",
                            IsActive = true,
                            ListPrice = 780m,
                            Price = 650m,
                            Price10 = 550m,
                            Price5 = 600m,
                            SKU = "SLEEP-003",
                            StockQuantity = 70,
                            Title = "露營充氣枕"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "高背包覆設計搭配透氣布料，適合長時間戶外休息使用。",
                            IsActive = true,
                            ListPrice = 2200m,
                            Price = 1850m,
                            Price10 = 1600m,
                            Price5 = 1720m,
                            SKU = "FURN-002",
                            StockQuantity = 45,
                            Title = "高背折疊露營椅"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "輕量鋁合金骨架搭配耐磨椅布，收納體積小，方便攜帶。",
                            IsActive = true,
                            ListPrice = 1600m,
                            Price = 1380m,
                            Price10 = 1180m,
                            Price5 = 1280m,
                            SKU = "FURN-003",
                            StockQuantity = 50,
                            Title = "輕量月亮椅"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "可快速展開的三層置物架，適合擺放炊具、食材與露營用品。",
                            IsActive = true,
                            ListPrice = 2400m,
                            Price = 1980m,
                            Price10 = 1720m,
                            Price5 = 1850m,
                            SKU = "FURN-004",
                            StockQuantity = 28,
                            Title = "三層折疊露營置物架"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "包含餐盤、碗與杯具，耐用且方便清潔，適合戶外用餐。",
                            IsActive = true,
                            ListPrice = 1200m,
                            Price = 980m,
                            Price10 = 820m,
                            Price5 = 900m,
                            SKU = "COOK-002",
                            StockQuantity = 55,
                            Title = "戶外琺瑯餐具四件組"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "可調整亮度與色溫的復古造型 LED 燈，適合帳篷與戶外桌面照明。",
                            IsActive = true,
                            ListPrice = 1680m,
                            Price = 1380m,
                            Price10 = 1180m,
                            Price5 = 1280m,
                            SKU = "LIGHT-001",
                            StockQuantity = 42,
                            Title = "復古 LED 露營燈"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "大容量行動電源，支援多裝置充電，適合露營與戶外活動使用。",
                            IsActive = true,
                            ListPrice = 2800m,
                            Price = 2380m,
                            Price10 = 2100m,
                            Price5 = 2250m,
                            SKU = "LIGHT-002",
                            StockQuantity = 32,
                            Title = "戶外行動電源 20000mAh"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Description = "透氣快乾材質，適合健行、露營與日常戶外活動穿著。",
                            IsActive = true,
                            ListPrice = 1200m,
                            Price = 980m,
                            Price10 = 820m,
                            Price5 = 900m,
                            SKU = "WEAR-002",
                            StockQuantity = 80,
                            Title = "快乾機能短袖上衣"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Description = "四向彈性布料搭配耐磨設計，適合健行與露營活動。",
                            IsActive = true,
                            ListPrice = 2200m,
                            Price = 1880m,
                            Price10 = 1620m,
                            Price5 = 1750m,
                            SKU = "WEAR-003",
                            StockQuantity = 65,
                            Title = "戶外彈性機能長褲"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Description = "寬帽簷設計提供戶外遮陽效果，使用透氣快乾材質。",
                            IsActive = true,
                            ListPrice = 980m,
                            Price = 780m,
                            Price10 = 650m,
                            Price5 = 720m,
                            SKU = "WEAR-004",
                            StockQuantity = 90,
                            Title = "防曬透氣漁夫帽"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            Description = "柔軟刷毛內層提供良好保暖效果，適合秋冬露營與戶外活動。",
                            IsActive = true,
                            ListPrice = 3200m,
                            Price = 2680m,
                            Price10 = 2320m,
                            Price5 = 2500m,
                            SKU = "WEAR-005",
                            StockQuantity = 48,
                            Title = "保暖刷毛機能外套"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            Description = "大容量耐用收納箱，可收納露營裝備，也可作為戶外桌面使用。",
                            IsActive = true,
                            ListPrice = 1800m,
                            Price = 1480m,
                            Price10 = 1280m,
                            Price5 = 1380m,
                            SKU = "ACC-001",
                            StockQuantity = 38,
                            Title = "多功能戶外收納箱"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            Description = "耐磨防潑水材質的大容量裝備袋，適合攜帶衣物與露營用品。",
                            IsActive = true,
                            ListPrice = 1500m,
                            Price = 1280m,
                            Price10 = 1080m,
                            Price5 = 1180m,
                            SKU = "ACC-002",
                            StockQuantity = 52,
                            Title = "防水戶外裝備袋"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            Description = "耐用鋁合金營繩調節器，可快速調整帳篷與天幕營繩張力。",
                            IsActive = true,
                            ListPrice = 520m,
                            Price = 420m,
                            Price10 = 350m,
                            Price5 = 380m,
                            SKU = "ACC-003",
                            StockQuantity = 100,
                            Title = "鋁合金營繩調節器組"
                        });
                });

            modelBuilder.Entity("ECommerce.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ECommerce.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ApplicationUserId", "ProductId")
                        .IsUnique();

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ECommerce.Models.OrderDetail", b =>
                {
                    b.HasOne("ECommerce.Models.OrderHeader", "OrderHeader")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Models.OrderHeader", b =>
                {
                    b.HasOne("ECommerce.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("ECommerce.Models.PaymentTransaction", b =>
                {
                    b.HasOne("ECommerce.Models.OrderHeader", "OrderHeader")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");
                });

            modelBuilder.Entity("ECommerce.Models.Product", b =>
                {
                    b.HasOne("ECommerce.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Models.ProductImage", b =>
                {
                    b.HasOne("ECommerce.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Models.ShoppingCart", b =>
                {
                    b.HasOne("ECommerce.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ECommerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ECommerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ECommerce.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Models.OrderHeader", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("ECommerce.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
