// <auto-generated />
using ECommerce.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Web.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "客廳家具"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "臥室家具"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "餐廳家具"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "書房家具"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "辦公家具"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "戶外家具"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "收納家具"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
