<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\ECommerce.DataAccess\ECommerce.DataAccess.csproj" />
    <ProjectReference Include="..\ECommerce.Models\ECommerce.Models.csproj" />
    <ProjectReference Include="..\ECommerce.Utility\ECommerce.Utility.csproj" />
  </ItemGroup>

</Project>
