name: Build and Push ECommerce Image

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: ecommercejamacr
  IMAGE_NAME: ecommerce-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Get ACR login server
        id: acr
        run: |
          LOGIN_SERVER=$(az acr show \
            --name ${{ env.ACR_NAME }} \
            --query loginServer \
            --output tsv)

          echo "login_server=$LOGIN_SERVER" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.acr.outputs.login_server }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -t ${{ steps.acr.outputs.login_server }}/${{ env.IMAGE_NAME }}:latest \
            .

      - name: Push Docker image
        run: |
          docker push ${{ steps.acr.outputs.login_server }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ steps.acr.outputs.login_server }}/${{ env.IMAGE_NAME }}:latest
